name: 'Create PR'
description: 'Parametrized composite action to create a pull request between branches.'
inputs:
  source_branch:
    description: 'The branch to merge from.'
    required: true
  target_branch:
    description: 'The branch to merge into.'
    required: true
  pr_title:
    description: 'Title for the pull request.'
    required: true
  pr_body:
    description: 'Body content for the pull request.'
    required: false
    default: ''

  
runs:
  using: 'composite'
  steps:
  
    - name: Create or update PR via gh CLI
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      run: |
        ACTION_RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        PR_JSON=$(gh pr \
          list \
          --base "${{ inputs.target_branch }}" \
          --head "${{ inputs.source_branch }}" \
          --state open \
          --json number,url
        )

        if [ "$(echo "$PR_JSON" | jq 'length')" -eq 0 ]; then
          ACTION="Created"
          PR_URL=$(gh pr create \
            --base "${{ inputs.target_branch }}" \
            --head "${{ inputs.source_branch }}" \
            --title "${{ inputs.pr_title }}" \
            --body "${{ inputs.pr_body }}" \
            --fill \
            | tail -n1)
          PR_NUMBER=$(basename "$PR_URL")
          
        else
          ACTION="Updated"
          PR_URL=$(echo "$PR_JSON" | jq -r '.[0].url')
          PR_NUMBER=$(echo "$PR_JSON" | jq -r '.[0].number')

          gh pr comment \
            $PR_NUMBER \
            --body "- 🚀 Updated PR from ${{ inputs.source_branch }} to ${{ inputs.target_branch }} from action run ${ACTION_RUN_URL}"
        fi

        echo "- 🚀 $ACTION PR from ${{ inputs.source_branch }} to ${{ inputs.target_branch }}: $PR_URL" >> $GITHUB_STEP_SUMMARY
