name: 'changesets-is-release-merge'
description: 'Detect if the current commit is a changeset-release merge commit.'
inputs:
  commit:
    description: 'The commit SHA to check.'
    required: true
  unshallow-checkout:
    description: 'If true, perform a full (unshallow) checkout with fetch-depth: 0. If false, assumes code is already checked out.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      if: ${{ inputs.unshallow-checkout == 'true' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Detect changeset-release ancestor
      id: check_changeset_release
      shell: bash
      run: |
        SCRIPT="${GITHUB_ACTION_PATH:-.}/detect-changeset-release.sh"
        chmod +x "$SCRIPT"
        bash "$SCRIPT" "${{ inputs.commit }}"

outputs:
  changesets-is-release-merge:
    description: 'True if this is a changeset-release merge commit.'
    value: ${{ steps.check_changeset_release.outputs.changesets-is-release-merge }}
