name: 'changesets-is-release-merge'
description: 'Detect if the current commit is a changeset-release merge commit.'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Detect changeset-release ancestor
      id: check_changeset_release
      shell: bash
      run: |
        git fetch --all
        # Get parent SHAs as array
        PARENTS=($(git rev-list --parents -n 1 $GITHUB_SHA | cut -d' ' -f2-))
        NUM_PARENTS=${#PARENTS[@]}

        if [ "$NUM_PARENTS" -ne 2 ]; then
          echo "changesets-is-release-merge=false" | tee -a $GITHUB_OUTPUT
          echo "- 🦋❌ Not a 2-parent merge commit: $GITHUB_SHA" | tee -a $GITHUB_STEP_SUMMARY
          exit 0
        fi

        IS_CHANGESET_RELEASE=false
        for parent in "${PARENTS[@]}"; do
          short_parent=$(echo $parent | cut -c1-7)
          echo "🔍 Checking parent commit: $short_parent" | tee -a $GITHUB_STEP_SUMMARY

          for branch in $(git branch -r --contains $parent | grep 'origin/changeset-release/'); do
            echo "└─ Considering changeset-release branch: $branch (for parent $short_parent)" | tee -a $GITHUB_STEP_SUMMARY

            TIP_SHA=$(git rev-parse "$branch")
            short_tip=$(echo $TIP_SHA | cut -c1-7)

            if [ "$parent" = "$TIP_SHA" ]; then
              IS_CHANGESET_RELEASE=true
              echo "✔️ Parent $short_parent matches tip of $branch ($short_tip)" | tee -a $GITHUB_STEP_SUMMARY
            fi
          done
        done

        echo "changesets-is-release-merge=$IS_CHANGESET_RELEASE" | tee -a $GITHUB_OUTPUT
outputs:
  changesets-is-release-merge:
    description: 'True if this is a changeset-release merge commit.'
    value: ${{ steps.check_changeset_release.outputs.changesets-is-release-merge }}
