name: 'Publish to NPM'
description: 'Build and publish package to NPM with commit SHA and latest tags.'
inputs:
  npm_token:
    description: 'NPM authentication token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Build package
      run: npm run build
      shell: bash
      
    - name: Publish to npm
      run: |
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        COMMIT_SHA=$(git rev-parse --short HEAD)

        [ "$BRANCH" != "main" ] && \
          npm version prerelease \
            --preid "$(echo "$BRANCH" | tr '/' '-')" \
            --no-git-tag-version

        PKG_NAME=$(npm pkg get name | tr -d '"')
        PKG_VERSION=$(npm pkg get version | tr -d '"')

        npm publish \
          --access public \
          --tag "$COMMIT_SHA"

        [ "$BRANCH" = "main" ] && \
          npm dist-tag \
            add "$PKG_NAME@$PKG_VERSION" latest

      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
