name: 'Publish Storybook to GitHub Pages'
description: 'Build and publish Storybook to GitHub Pages using Bitovi action.'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Publish Storybook to GitHub Pages
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      with:
        install_command: yarn install # default: npm ci
        build_command: yarn build-storybook # default: npm run build-storybook
        path: storybook-static # default: dist/storybook
        checkout: false # default: true