name: Build & Push Devcontainer Image

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract repository name in lowercase
        id: repo
        run: |
          echo "image_name=${GITHUB_REPOSITORY,,}-devcontainer" >> $GITHUB_OUTPUT

      - name: Extract version from package.json
        id: version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.image_name }}:latest
            ghcr.io/${{ steps.repo.outputs.image_name }}:${{ steps.version.outputs.version }}
            ghcr.io/${{ steps.repo.outputs.image_name }}:${{ github.sha }}

      - name: Output image URLs to summary
        run: |
          echo "### 📦 Devcontainer Image URLs" >> $GITHUB_STEP_SUMMARY

          echo "Published the following tags (visit https://ghcr.io/${{ steps.repo.outputs.image_name }}):" >> $GITHUB_STEP_SUMMARY

          echo '- `ghcr.io/${{ steps.repo.outputs.image_name }}:latest`' >> $GITHUB_STEP_SUMMARY
          echo '- `ghcr.io/${{ steps.repo.outputs.image_name }}:${{ github.sha }}`' >> $GITHUB_STEP_SUMMARY
          echo '- `ghcr.io/${{ steps.repo.outputs.image_name }}:${{ steps.version.outputs.version }}`' >> $GITHUB_STEP_SUMMARY
