name: Build and Publish Docker Images

on:
  push:
    branches: ["**"]
    paths:
      - Dockerfile
      - package.json
      - package-lock.json
      - .github/workflows/docker-publish.yml
      - src/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag
        id: vars
        run: |
          BRANCH=$(echo "${GITHUB_REF##*/}" | tr / -)
          echo "tag=$BRANCH" >> $GITHUB_OUTPUT

      - name: Build and push Storybook image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: storybook-build
          push: true
          tags: ghcr.io/${{ github.repository }}/storybook:${{ steps.vars.outputs.tag }}

      - name: Build and push Vitest cache image (optional)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: vitest-cache
          push: true
          tags: ghcr.io/${{ github.repository }}/vitest-cache:${{ steps.vars.outputs.tag }}
