name: Publish Package to npm

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: ["**"]

jobs:
  build-and-publish:
    name: Build and Publish NPM Package
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish
        uses: ./.github/actions/node-publish
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
