name: Run Vitest

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: Run Vitest
    runs-on: ubuntu-latest
    steps:
      - name: Run composite test action
        uses: ./.github/actions/test
